export const GET_GEOLOCATION = 'GET_GEOLOCATION';
export const GET_GEOLOCATION_SUCCES = 'GET_GEOLOCATION_SUCCES';
export const GET_GEOLOCATION_FAIL = 'GET_GEOLOCATION_FAIL';

export const GET_GPS = 'GET_GPS';
export const GET_GPS_SUCCES = 'GET_GPS_SUCCES';
export const GET_GPS_FAIL = 'GET_GPS_FAIL';